# Dependencies
markdown:         redcarpet
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            mdw
tagline:          'mdw on github'
description:      'Trying to make a new page'
url:              http://mdwelsh.github.io
baseurl:          /

author:
  name:           'Matt Welsh'
  url:            http://www.mdw.la

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/mdwelsh/mdwelsh.github.io
